---
- hosts: webserver
  remote_user: patmat
  become: yes
  become_method: sudo
  tasks: 
    - 
      name: "install packages using loop"
      package: 
        name: "{{ item }}"
        state: present 
      with_items: 
        - httpd
        - php
        - telnet
        - traceroute
